version = "Two"
use_field_init_shorthand = true

unstable_features = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
normalize_doc_attributes = true
normalize_comments = true
wrap_comments = true
format_code_in_doc_comments = true
condense_wildcard_suffixes = true
overflow_delimited_expr = true
reorder_impl_items = true
