[package]
name = "cli"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { version = "1.29", features = ["macros", "rt-multi-thread"] }
shlex = "1.1"
zbus = "3.14"
clap = { version = "4.3", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
anyhow = "1"
