[package]
name = "daemon"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { version = "1.29", features = ["macros", "rt-multi-thread"] }
zbus = "3.14"
env_logger = "0.10"
log = "0.4"
